// Defines the structure for an Agent object, mirroring your backend's AgentDto.
export interface Agent {
    id?: number; // Optional as it's generated by the backend
    name: string;
    email: string;
    currentAssignedTicketsCount?: number; // Optional, derived field
  }
  